modLoader="javafml"
loaderVersion="${neoForgeLoaderVersion}"
license="${license}"

[[mods]]
modId="animated_doors"
version="${version}"
displayName="${name}"
description='''${description}'''
authors="${author}"
logoFile="assets/animated_doors/icon.png"

[[mixins]]
config="animated_doors.mixins.json"

[[dependencies.animated_doors]]
modId="neoforge"
type="required"
versionRange="[${neoForgeVersion},)"
ordering="NONE"
side="CLIENT"

[[dependencies.animated_doors]]
modId="minecraft"
type="required"
versionRange="${neoForgeSupportedVersions}"
ordering="NONE"
side="CLIENT"
